# Crypto material for SM — generated by OpenTofu (not GitHub, not manual seed).
resource "random_password" "csrf" {
  length  = 48
  special = false
}

resource "random_password" "cookie_hash" {
  length  = 48
  special = false
}

resource "random_password" "cookie_block" {
  length  = 48
  special = false
}

resource "random_password" "hydra_webhook_psk" {
  length  = 48
  special = false
}

locals {
  generated_secret_values = {
    "identity-authentication-csrf-secret"       = random_password.csrf.result
    "identity-authentication-cookie-hash-key"   = random_password.cookie_hash.result
    "identity-authentication-cookie-block-key"  = random_password.cookie_block.result
    "hydra-webhook-psk"                         = random_password.hydra_webhook_psk.result
  }
}
