# Crypto material for SM — generated by OpenTofu.
# hydra-webhook-psk is owned by identity-oauth2-hydra (shared secret id).
resource "random_password" "csrf" {
  length  = 48
  special = false
}

resource "random_password" "cookie_hash" {
  length  = 48
  special = false
}

resource "random_password" "cookie_block" {
  length  = 48
  special = false
}

locals {
  generated_secret_values = {
    "identity-authentication-csrf-secret"      = random_password.csrf.result
    "identity-authentication-cookie-hash-key"  = random_password.cookie_hash.result
    "identity-authentication-cookie-block-key" = random_password.cookie_block.result
  }
}
