# Crypto material for SM — generated by OpenTofu.
# hydra-webhook-psk is owned by identity-oauth2-hydra (shared secret id).
#
# SECURE_COOKIE_* keys are hex-decoded by service-authentication (gorilla securecookie).
# Use random_bytes → .hex (not random_password alphanumeric).

resource "random_password" "csrf" {
  length  = 48
  special = false
}

# 32 raw bytes → 64 hex chars (AES-256 block key / strong hash key)
resource "random_bytes" "cookie_hash" {
  length = 32
}

resource "random_bytes" "cookie_block" {
  length = 32
}

locals {
  generated_secret_values = {
    "identity-authentication-csrf-secret"      = random_password.csrf.result
    "identity-authentication-cookie-hash-key"  = random_bytes.cookie_hash.hex
    "identity-authentication-cookie-block-key" = random_bytes.cookie_block.hex
  }
}
